### ISSUE TITLE
allow to enable/disable JS for a specific URLs or masks, like example.com/articles/*

### ISSUE THREAD

**Issue by alon-to** [mtimkovich/quick-javascript-switcher2#1]
Excited to see someone might be working on this invaluable extension!

My feature request: allow to whitelist / blacklist individual URLs or URL masks. This is described well in https://github.com/maximelebreton/quick-javascript-switcher/pull/25.

For some reason non of the one-click javascript switchers support this feature, so this would be a game changer. Thanks!

**Comment by mtimkovich** [comment]
I think you meant https://github.com/maximelebreton/quick-javascript-switcher/issues/13?

Do you do this often? It seems like the sort of thing that you'd want to edit the rules list manually.

I could use your assistance mocking out how you'd like this feature to be enabled, I don't feel like I have a strong grasp of what you'd like to be added.

**Comment by alon-to** [comment]
Yes, https://github.com/maximelebreton/quick-javascript-switcher/issues/13!

Perhaps it's user error on my part, but going to QJS options there are "Local Storage rules" that look like:

`{"primaryPattern":"https://www.cnet.com/*","setting":"block","scope":"regular"}`

Ideally I'd be able to do one or both of the following:
* Replace `https://www.cnet.com/*` with `https://www.cnet.com/politics/*`, blocking javascript for any pages with /politics/ URLs but allowing it on any cnet.com/sports/* URLs
* Add support for an `allow` parameter instead of `block`. This Would allow me to block https://www.cnet.com/* but allow on one URL such as https://www.cnet.com/topnews.html. I haven't thought through how conflicting rules would work but hopefully there's some reasonably simple logic here.

Thanks!

**Comment by mtimkovich** [comment]
I did some research into this, and Chrome's default JS rules don't allow matches this complex. That means it would require me to implement those rules manually which goes beyond the scope of this "one click" extension.
