### ISSUE TITLE
Quick Javascript Switcher 2?

### ISSUE THREAD

**Issue by maximelebreton** [mtimkovich/quick-javascript-switcher2#2]
Hello @mtimkovich,

Thanks for your fork, but please, can you respect semantic versioning, and don't tell your fork `Quick Javascript Switcher 2`.
Your fork is not a `MAJOR` version, but a `PATCH` version (or at most a `MINOR`).
`1.4.2`, or `1.5.0`, but not `2`.

Furthermore, I have [plans for a next release](https://github.com/maximelebreton/quick-javascript-switcher/issues/35) (who will be a major version), so this is not pertinent, especially on the [Chrome webstore](https://chrome.google.com/webstore/detail/quick-javascript-switcher/ahjfodbngfpdppljbkhcfhcfdagfgcnj), users will be confused...

Thank you for your cooperation :)

**Comment by perpetual-hydrofoil** [comment]
Of course, it was very good of @mtimkovich to step up when you were AWOL too! Perhaps @maximelebreton and @mtimkovich can work together... especially after what happened with stylish. Thanks @maximelebreton for not becoming evil.

**Comment by maximelebreton** [comment]
Yep, and for the next release, I will use a different workflow (with code splitting, tests, and best practices), to make pull requests easier! (which is not the case with the actual worflow...)

**Comment by mtimkovich** [comment]
Sure. Will do. I hope you include things from this fork (like the right-click toggle) so this fork becomes obsolete!

**Comment by mtimkovich** [comment]
d5c97cef4e58586ca6a542ec0a6da59be0d3c246
