### ISSUE TITLE
JS toggle hotkey collides with browser default hotkey

### ISSUE THREAD

**Issue by mmmmgh** [mtimkovich/quick-javascript-switcher2#3]
It is nice to have a JS toggle hotkey. However the current one (ctrl-w) collides with the browser's hotkey for closing the current window which I happen to use regularly.

Therefore: Would you care to add a configurable hotkey for this extension?

PS: Since Maximelebreton is still AWOL :-) I'm trying my luck here, which is the most active fork of maximelebreton/quick-javascript-switcher

**Comment by mtimkovich** [comment]
That's strange, the default shortcut should be Alt-Shift-Q. You can change the shortcut to whatever you want from chrome://extensions/shortcuts.

**Comment by mmmmgh** [comment]
Thank you for pointing me to chrome://extensions/shortcuts (it's not easy to find this via google)!
And yes, your fork uses Alt-Shift-Q per default - don't know how that escaped me after having swapped maximelebreton/quick-javascript-switcher with one-click-javascript-toggle.
Keyboard shortcut Ctrl-w now works as expected in my Chromium.
Cheers, Michael

**Comment by mtimkovich** [comment]
Perfect!
